/** Comment placed at the top of every generated block in a plugin README. */
export const GENERATED_NOTE = '<!-- Generated by pumpkin-plugins-docs. Edit src/info.ts, then run `pnpm readme`. -->';

/**
 * Replaces the content between `<!-- docs:begin NAME -->` and `<!-- docs:end NAME -->` for each
 * entry in `blocks`. A block the text doesn't contain is skipped, so a README can opt out of a
 * section by leaving its markers out.
 * @param text - The README.
 * @param blocks - New content by block name.
 * @param file - The README's path, for error messages.
 * @param note - The comment to put at the top of each block.
 * @returns The README with the blocks replaced.
 * @throws {Error} When a block's markers are unbalanced, duplicated or out of order.
 */
export function applyBlocks(text: string, blocks: Record<string, string>, file: string, note = GENERATED_NOTE): string {
    let out = text;
    for (const [name, body] of Object.entries(blocks)) {
        const begin = `<!-- docs:begin ${name} -->`;
        const end = `<!-- docs:end ${name} -->`;
        const starts = out.split(begin).length - 1;
        const ends = out.split(end).length - 1;
        if (starts === 0 && ends === 0) continue;
        if (starts !== 1 || ends !== 1) {
            throw new Error(`${file}: expected exactly one "${begin}" and one "${end}", found ${starts} and ${ends}`);
        }
        const from = out.indexOf(begin);
        const to = out.indexOf(end);
        if (to < from) throw new Error(`${file}: "${end}" comes before "${begin}"`);
        out = `${out.slice(0, from)}${begin}\n${note}\n\n${body}\n${end}${out.slice(to + end.length)}`;
    }
    return out;
}
