import * as fs from 'node:fs';
import * as path from 'node:path';
import { pathToFileURL } from 'node:url';
import { applyBlocks } from './blocks.ts';
import type { PluginInfo } from './info.ts';
import { type ActionRow, type PackageRow, ROOT_NOTE, renderPackagesBlock } from './packages.ts';
import { renderBlocks } from './sections.ts';
import { githubPagesUrl } from './site.ts';

const REFERENCE_NOTE =
    '<!-- Generated by pumpkin-plugins-docs from package, action, and component docs metadata. Run `pnpm readme`. -->';

/** What happened to a README. `stale` is only reported when checking: nothing was written. */
export type Status = 'updated' | 'unchanged' | 'stale';

const readJson = (file: string) => JSON.parse(fs.readFileSync(file, 'utf8'));

function infoPath(pluginDir: string): string {
    const pkg = readJson(path.join(pluginDir, 'package.json'));
    return path.resolve(pluginDir, pkg.pumpkinPlugin?.info ?? 'src/info.ts');
}

/**
 * Loads the `info` export of a plugin's info module. Node strips the TypeScript types.
 * @param pluginDir - The plugin's folder.
 * @returns What the plugin says about itself.
 * @throws {Error} When the module is missing or doesn't export a usable `info`.
 */
export async function loadInfo(pluginDir: string): Promise<PluginInfo> {
    const file = infoPath(pluginDir);
    if (!fs.existsSync(file)) {
        throw new Error(`${file} not found: a plugin needs a src/info.ts that exports \`info\``);
    }
    const mod = await import(pathToFileURL(file).href);
    const info = mod.info ?? mod.default;
    if (typeof info?.name !== 'string' || typeof info?.description !== 'string') {
        throw new Error(`${file} must export an \`info\` object with a name and a description`);
    }
    return info;
}

function readReadme(file: string, hint: string): string {
    if (!fs.existsSync(file)) throw new Error(`${file} not found. ${hint}`);
    return fs.readFileSync(file, 'utf8');
}

function write(file: string, existing: string, next: string, check: boolean): Status {
    if (existing === next) return 'unchanged';
    if (check) return 'stale';
    fs.writeFileSync(file, next);
    return 'updated';
}

function requireBlock(text: string, file: string, name: string): void {
    const begin = `<!-- docs:begin ${name} -->`;
    const end = `<!-- docs:end ${name} -->`;
    if (!text.includes(begin) || !text.includes(end)) {
        throw new Error(`${file} needs a ${begin} / ${end} block`);
    }
}

function routeUrl(siteUrl: URL, route: string): string {
    return new URL(encodeURI(route), siteUrl).href;
}

interface ComponentReference {
    file: string;
    apiRoute: string;
    guideRoute?: string;
    guideLabel: string;
}

interface ReadmeUpdate {
    file: string;
    existing: string;
    next: string;
}

async function packageReferences(root: string, group: 'packages' | 'tools'): Promise<ComponentReference[]> {
    const base = path.join(root, group);
    if (!fs.existsSync(base)) return [];

    const references: ComponentReference[] = [];
    for (const entry of fs.readdirSync(base, { withFileTypes: true })) {
        if (!entry.isDirectory() || entry.name.startsWith('_')) continue;
        const directory = path.join(base, entry.name);
        const manifestFile = path.join(directory, 'package.json');
        const readme = path.join(directory, 'README.md');
        if (!fs.existsSync(manifestFile) || !fs.existsSync(path.join(directory, 'src')) || !fs.existsSync(readme)) {
            continue;
        }

        const manifest = readJson(manifestFile);
        if (group === 'packages' && !manifest.pumpkinPlugin) continue;
        if (group === 'packages') await loadInfo(directory);
        if (typeof manifest.name !== 'string' || !manifest.name) continue;

        const docsIndex = path.join(directory, 'docs', 'index.md');
        references.push({
            file: readme,
            apiRoute: group === 'packages' ? `api/plugins/${entry.name}/` : `api/tools/${manifest.name}/`,
            ...(fs.existsSync(docsIndex) ? { guideRoute: `${group}/${entry.name}/docs/` } : {}),
            guideLabel: group === 'packages' ? 'plugin guide' : 'tool guide'
        });
    }
    return references;
}

function actionReferences(root: string): ComponentReference[] {
    return actionRows(root).flatMap(({ dir }) => {
        const slug = path.basename(dir);
        const directory = path.join(root, dir);
        const file = path.join(directory, 'README.md');
        if (!fs.existsSync(file) || !fs.existsSync(path.join(directory, 'src'))) return [];
        return [
            {
                file,
                apiRoute: `api/actions/${slug}/`,
                ...(fs.existsSync(path.join(directory, 'docs', 'index.md'))
                    ? { guideRoute: `actions/${slug}/docs/` }
                    : {}),
                guideLabel: 'action guide'
            }
        ];
    });
}

async function prepareComponentReferenceUpdates(root: string, siteUrl: URL): Promise<ReadmeUpdate[]> {
    const references = [
        ...(await packageReferences(root, 'packages')),
        ...(await packageReferences(root, 'tools')),
        ...actionReferences(root)
    ];
    const updates: ReadmeUpdate[] = [];
    for (const reference of references) {
        const existing = readReadme(reference.file, 'Add a generated references block to component READMEs.');
        requireBlock(existing, reference.file, 'reference');
        const apiUrl = routeUrl(siteUrl, reference.apiRoute);
        const apiLink = `[API reference](${apiUrl})`;
        const body = reference.guideRoute
            ? `See the [${reference.guideLabel}](${routeUrl(siteUrl, reference.guideRoute)}) and ${apiLink} on the documentation site.`
            : `See the ${apiLink} on the documentation site.`;
        const next = applyBlocks(existing, { reference: body }, reference.file, REFERENCE_NOTE);
        updates.push({ file: reference.file, existing, next });
    }
    return updates;
}

function combinedStatus(statuses: Status[]): Status {
    if (statuses.includes('stale')) return 'stale';
    if (statuses.includes('updated')) return 'updated';
    return 'unchanged';
}

/**
 * Refreshes the generated blocks of a plugin's README. Everything outside the blocks is kept.
 * @param pluginDir - The plugin's folder.
 * @param check - Only report whether the README is out of date, without writing.
 * @returns What happened to the README.
 * @throws {Error} When the README doesn't exist. `pnpm gen` creates one for new plugins.
 */
export async function generatePluginReadme(pluginDir: string, check = false): Promise<Status> {
    const info = await loadInfo(pluginDir);
    const file = path.join(pluginDir, 'README.md');
    const existing = readReadme(
        file,
        'Create it with <!-- docs:begin NAME --> blocks, as `pnpm gen` does for a new plugin.'
    );
    return write(file, existing, applyBlocks(existing, renderBlocks(info), file), check);
}

async function rows(root: string, group: 'packages' | 'tools'): Promise<PackageRow[]> {
    const base = path.join(root, group);
    if (!fs.existsSync(base)) return [];
    const out: PackageRow[] = [];
    for (const entry of fs.readdirSync(base, { withFileTypes: true })) {
        const dir = path.join(base, entry.name);
        if (!entry.isDirectory() || !fs.existsSync(path.join(dir, 'package.json'))) continue;
        const pkg = readJson(path.join(dir, 'package.json'));
        // Plugins are shown by their Pumpkin name and description when they define them.
        const info = group === 'packages' && fs.existsSync(infoPath(dir)) ? await loadInfo(dir) : undefined;
        const licenseFile = fs
            .readdirSync(dir, { withFileTypes: true })
            .find((file) => file.isFile() && /^license(?:\.md|\.txt)?$/i.test(file.name));
        out.push({
            dir: `${group}/${entry.name}`,
            name: info?.name ?? pkg.name,
            description: info?.description ?? pkg.description ?? '',
            license: pkg.license ?? '',
            licenseFile: licenseFile ? `${group}/${entry.name}/${licenseFile.name}` : undefined
        });
    }
    return out;
}

function actionScalar(contents: string, key: 'name' | 'description', file: string): string {
    const lines = contents.split(/\r?\n/);
    const index = lines.findIndex((entry) => new RegExp(`^${key}:`).test(entry));
    if (index < 0) throw new Error(`${file} is missing its top-level ${key}`);

    const value = lines[index].slice(key.length + 1).trim();
    let parsed: string;
    const block = value.match(/^([>|])(?:[+-][1-9]?|[1-9][+-]?|[+-])?(?:\s+#.*)?$/);
    if (block) {
        const body: string[] = [];
        for (const line of lines.slice(index + 1)) {
            if (!line.trim()) {
                if (body.length) body.push('');
                continue;
            }
            const indent = line.length - line.trimStart().length;
            if (!indent) break;
            body.push(line.slice(indent));
        }
        parsed = body.join(block[1] === '>' ? ' ' : '\n').trim();
    } else if (value.startsWith('"')) {
        const match = value.match(/^((?:"(?:[^"\\]|\\.)*"))(?:\s+#.*)?$/);
        if (!match) throw new Error(`${file} needs a single-line ${key} value`);
        try {
            parsed = JSON.parse(match[1]) as string;
        } catch {
            throw new Error(`${file} has an invalid quoted ${key}`);
        }
    } else if (value.startsWith("'")) {
        const match = value.match(/^'((?:[^']|'')*)'(?:\s+#.*)?$/);
        if (!match) throw new Error(`${file} needs a single-line ${key} value`);
        parsed = match[1].replace(/''/g, "'");
    } else {
        parsed = value.replace(/\s+#.*$/, '').trim();
    }
    if (!parsed.trim()) throw new Error(`${file} has an empty ${key}`);
    return parsed;
}

function actionRows(root: string): ActionRow[] {
    const base = path.join(root, 'actions');
    if (!fs.existsSync(base)) return [];
    const out: ActionRow[] = [];
    for (const entry of fs.readdirSync(base, { withFileTypes: true })) {
        if (!entry.isDirectory()) continue;
        const dir = path.join(base, entry.name);
        const metadata = ['action.yml', 'action.yaml']
            .map((file) => path.join(dir, file))
            .find((file) => fs.existsSync(file));
        if (!metadata) continue;
        const contents = fs.readFileSync(metadata, 'utf8');
        out.push({
            dir: `actions/${entry.name}`,
            name: actionScalar(contents, 'name', metadata),
            description: actionScalar(contents, 'description', metadata)
        });
    }
    return out;
}

/**
 * Refreshes the actions, plugin and tool tables in the repo's root README.
 * @param root - The repository root.
 * @param check - Only report whether the README is out of date, without writing.
 * @returns What happened to the README.
 * @throws {Error} When the README or its `packages` block is missing.
 */
export async function generateRootReadme(root: string, check = false): Promise<Status> {
    const file = path.join(root, 'README.md');
    const existing = readReadme(file, 'The repository needs a README with a packages block.');
    if (!existing.includes('<!-- docs:begin packages -->')) {
        throw new Error(`${file} needs a <!-- docs:begin packages --> / <!-- docs:end packages --> block`);
    }
    requireBlock(existing, file, 'docs-site');
    const rootPackage = readJson(path.join(root, 'package.json'));
    const siteUrl = githubPagesUrl(rootPackage.repository);
    if (!siteUrl)
        throw new Error(`${path.join(root, 'package.json')} needs a GitHub repository URL for documentation links`);
    const block = renderPackagesBlock(await rows(root, 'packages'), await rows(root, 'tools'), actionRows(root));
    const next = applyBlocks(
        existing,
        {
            packages: block,
            'docs-site': `Browse the [public documentation site](${siteUrl.href}) for guides, component overviews, and generated API references.`
        },
        file,
        ROOT_NOTE
    );
    const updates = [{ file, existing, next }, ...(await prepareComponentReferenceUpdates(root, siteUrl))];
    return combinedStatus(updates.map((update) => write(update.file, update.existing, update.next, check)));
}
