import { table } from './markdown.ts';

/** One row of the package tables in the root README. */
export interface PackageRow {
    /** Folder relative to the repo root, such as `packages/my-plugin`. */
    dir: string;
    /** Name shown as the link text. */
    name: string;
    /** One-line description. */
    description: string;
}

/** Comment placed at the top of the generated packages block in the root README. */
export const ROOT_NOTE =
    "<!-- Generated by pumpkin-plugins-docs from each package's package.json. Run `pnpm readme`. -->";

/**
 * Renders the plugin and tool tables for the root README.
 * @param plugins - The packages in `packages/`.
 * @param tools - The packages in `tools/`.
 * @returns Markdown with one linked row per package, sorted by folder.
 */
export function renderPackagesBlock(plugins: PackageRow[], tools: PackageRow[]): string {
    const rows = (list: PackageRow[]) =>
        [...list].sort((a, b) => a.dir.localeCompare(b.dir)).map((p) => [`[${p.name}](${p.dir})`, p.description]);
    return [
        '**Plugins**',
        '',
        table(['Plugin', 'Description'], rows(plugins)),
        '',
        '**Tools**',
        '',
        table(['Package', 'Description'], rows(tools))
    ].join('\n');
}
