import { table } from './markdown.ts';

/** One row of the package tables in the root README. */
export interface PackageRow {
    /** Folder relative to the repo root, such as `packages/my-plugin`. */
    dir: string;
    /** Name shown as the link text. */
    name: string;
    /** One-line description. */
    description: string;
    /** License identifier from package.json. */
    license: string;
    /** Package-specific license file relative to the repo root, when present. */
    licenseFile?: string;
}

/** One row of the action table in the root README. */
export interface ActionRow {
    /** Folder relative to the repo root, such as `actions/my-action`. */
    dir: string;
    /** Name shown as the link text. */
    name: string;
    /** One-line description. */
    description: string;
}

/** Comment placed at the top of the generated catalog block in the root README. */
export const ROOT_NOTE =
    '<!-- Generated by pumpkin-plugins-docs from action metadata and package metadata. Run `pnpm readme`. -->';

/**
 * Renders the action, plugin and tool tables for the root README.
 * @param plugins - The packages in `packages/`.
 * @param tools - The packages in `tools/`.
 * @param actions - The actions in `actions/`.
 * @returns Markdown with linked rows sorted by folder.
 */
export function renderPackagesBlock(plugins: PackageRow[], tools: PackageRow[], actions: ActionRow[] = []): string {
    const packageRows = (list: PackageRow[]) =>
        [...list]
            .sort((a, b) => a.dir.localeCompare(b.dir))
            .map((p) => [
                `[${p.name}](${p.dir})`,
                p.description,
                p.licenseFile ? `[${p.license}](${p.licenseFile})` : p.license
            ]);
    const sections: string[] = [];
    if (actions.length) {
        sections.push(
            [
                '**Actions**',
                '',
                table(
                    ['Action', 'Description'],
                    [...actions]
                        .sort((a, b) => a.dir.localeCompare(b.dir))
                        .map((action) => [`[${action.name}](${action.dir})`, action.description])
                )
            ].join('\n')
        );
    }
    sections.push(
        [
            '**Plugins**',
            '',
            table(['Plugin', 'Description', 'License'], packageRows(plugins)),
            '',
            '**Tools**',
            '',
            table(['Package', 'Description', 'License'], packageRows(tools))
        ].join('\n')
    );
    return sections.join('\n\n');
}
